import 'package:flutter/material.dart';

class AppIcons {
  static String iconPath(String ico, [String ext]) =>
      'assets/icons/$ico.${ext ?? "png"}';
  static String get qrCode => iconPath('qr_code');
  static String get qrCode1 => iconPath('qr_code_1');
  static String get qrCode2 => iconPath('qr_code_2');
  static String get personQR => iconPath('qr');
  static String get fuel => iconPath('fuel');
  static String get beneficiaries => iconPath('beneficiaries');
  static String get policy => iconPath('policy');
  static String get transactions => iconPath('transactions');
  static String get contact => iconPath('contact');
  static String get scanQrCode => iconPath('scan_qr_code');
  static String get bell => iconPath('bell');
  static String get caretDown => iconPath('caret_down');
  static String get menu => iconPath('menu');
  static String get transaction => iconPath('transaction');
  static String get wallet => iconPath('wallet');
  static String get card => iconPath('card');
  static String get transactionGreen => iconPath('transaction_green');
  static String get cardRed => iconPath('card_red');
  static String get walletGreen => iconPath('wallet_green');
  static String get electricity => iconPath('electricity');
  static String get loan => iconPath('loan');
  static String get send => iconPath('send');
  static String get topup => iconPath('topup');
  static String get chat => iconPath('chat');
  static String get scan => iconPath('scan');
  static String get tv => iconPath('tv');
  static String get utilities => iconPath('utilities');
  static String get list => iconPath('list');
  static String get stories => iconPath('stories');
  static String get people => iconPath('people');
  static String get lock => iconPath('lock');
  static String get notes => iconPath('notes');
  static String get umemeIcon => iconPath('umeme_icon');
  static String get icon => iconPath('icon');
  static String get call => iconPath('call-calling');
  static String get fb => iconPath('facebook');
  static String get web => iconPath('global-search');
  static String get headset => iconPath('headset');
  static String get list2 => iconPath('menu-board');
  static String get message => iconPath('message-text');
  static String get sms => iconPath('sms');
  static String get twitter => iconPath('twitter');
  static String get searchWhite => iconPath('search_white');
  static String get check => iconPath('check');
  static String get greenCheck => iconPath('green_check');
  static String get trash => iconPath('trash');
}

class AppImages {
  static String imagePath(String img, [String ext]) =>
      'assets/images/$img.${ext ?? "png"}';
  static String get logo => imagePath('logo');
  static String get pivotPayLogo => imagePath('pivot_pay');
  static String get badgeLayer => imagePath('badge_layer');
  static String get pPayLogo => imagePath('pPayLogo');
  static String get pPayLogo2 => imagePath('pPayLogo2');
  static String get pivotPayLogo2 => imagePath('pivot_pay2');
  static String get logo2 => imagePath('white_logo');
  static String get onboarding => imagePath('onboarding', 'gif');
  static String get sad => imagePath('failed');
  static String get failed => imagePath('sad', 'json');
  static String get processing => imagePath('processing');
  static String get refresh => imagePath('refresh', 'gif');
  static String get onboarding2 => imagePath('onboarding2');
  static String get kudos => imagePath('kudos');
  static String get loading => imagePath('loading', 'json');
  static String get success => imagePath('success', 'json');
  static String get person1 => imagePath('person1');
  static String get splashImg => imagePath('splash_img');
  static String get splashImage => imagePath('splash_page');
  static String get person2 => imagePath('person2');
  static String get mastercard => imagePath('mastercard');
  static String get btnWave => imagePath('btn_wave');
  static String get blob1 => imagePath('blob1');
  static String get blob2 => imagePath('blob2');
  static String get blob3 => imagePath('blob3');
  static String get shieldTick => imagePath('shield_tick');
  static String get hand => imagePath('hand');
  static String get mtn => imagePath('mtn');
  static String get airtel => imagePath('airtel');
  static String get bodaboda => imagePath('bodaboda');
  static String get umeme => imagePath('umeme');
  static String get dstv => imagePath('dstv');
  static String get tv => imagePath('tv');
  static String get contactless => imagePath('contactless');
  static String get wenreco => imagePath('wenreco');
  static String get nwsc => imagePath('nwsc');
  static String get phoneIcon => imagePath('phone_icon');
  static String get sim => imagePath('sim');
  static String get flash => imagePath('flash');
  static String get xmas => imagePath('xmas');
  static String get uganda => imagePath('uganda');
  static String get kenya => imagePath('kenya');
  static String get nigeria => imagePath('nigeria', 'jpg');
  static String get pivotPayts => imagePath('pivotPaytsLogo');
  static String get waves => imagePath('waves');
  static String get pplogo => imagePath('pivot-logo');
  static String get pattern1 => imagePath('pattern1');
  static String get pattern2 => imagePath('pattern2');
  static String get pattern3 => imagePath('pattern3');
}

class AppColors {
  static Color get redColor => Color(0xFFDF2030);
  static Color get primaryColor => Color(0xFF034c81);
  static Color get brandColor => Color.fromARGB(255, 230, 162, 60);
  static Color get pivotPayColorGreen => Color(0xFF85BA33);
  static Color get dashboardColor => Color.fromARGB(255, 26, 63, 86);
  static Color get headerColor => Color.fromARGB(255, 241, 85, 35);
  static Color get scaffoldColor => Colors.white;
  static Color get errorColor => Color(0xFFFE1B02);
  static Color get lightGrey => Color(0xFFD2D2D2);
  static Color get greyColor => Color(0xFF727272).withOpacity(0.48);
  static Color get greyColor2 => Color(0xFF5c5c5c);
  static Color shimmer_base = Colors.grey.shade50;
  static Color shimmer_highlighted = Colors.grey.shade200;
  static Color noColor = Color.fromRGBO(255, 255, 255, 0);
  static Color soft_accent_color = Color.fromRGBO(254, 234, 209, 1);
  static Color accent_color = Color.fromRGBO(230, 46, 4, 1);
  static Color get appBarColor => Color.fromARGB(255, 23, 38, 53);
}
